[build]
command = 'npm run build'
functions = 'functions'
publish = 'build'

[functions]
directory = ".netlify/functions"
included_files = ["README.md"]

[[redirects]]
from = "/api/v1/*"
to = "https://glass-art-gallery.herokuapp.com/api/v1/:splat"
status = 200
